/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OldreviewImport } from './routes/oldreview'
import { Route as IndexImport } from './routes/index'
import { Route as ReviewPaperIdImport } from './routes/review.$paperId'

// Create/Update Routes

const OldreviewRoute = OldreviewImport.update({
  id: '/oldreview',
  path: '/oldreview',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ReviewPaperIdRoute = ReviewPaperIdImport.update({
  id: '/review/$paperId',
  path: '/review/$paperId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/oldreview': {
      id: '/oldreview'
      path: '/oldreview'
      fullPath: '/oldreview'
      preLoaderRoute: typeof OldreviewImport
      parentRoute: typeof rootRoute
    }
    '/review/$paperId': {
      id: '/review/$paperId'
      path: '/review/$paperId'
      fullPath: '/review/$paperId'
      preLoaderRoute: typeof ReviewPaperIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/oldreview': typeof OldreviewRoute
  '/review/$paperId': typeof ReviewPaperIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/oldreview': typeof OldreviewRoute
  '/review/$paperId': typeof ReviewPaperIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/oldreview': typeof OldreviewRoute
  '/review/$paperId': typeof ReviewPaperIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/oldreview' | '/review/$paperId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/oldreview' | '/review/$paperId'
  id: '__root__' | '/' | '/oldreview' | '/review/$paperId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OldreviewRoute: typeof OldreviewRoute
  ReviewPaperIdRoute: typeof ReviewPaperIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OldreviewRoute: OldreviewRoute,
  ReviewPaperIdRoute: ReviewPaperIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/oldreview",
        "/review/$paperId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/oldreview": {
      "filePath": "oldreview.tsx"
    },
    "/review/$paperId": {
      "filePath": "review.$paperId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
